In [1]:
import pandas as pd

# 学生过程线名单

In [3]:
exam_info = pd.read_excel('C:\\Users\\caozhiqiang\\Desktop\\考试数据分析\\北京四中数据\\20-21第二学期一模考试\\整理数据\\学生成绩.xlsx')
exam_info.head()

,姓名,学号,班级,考试名称,语文,数学,英语,三科,物理,化学,历史,生物,地理,政治,全科,Unnamed: 15
0,谢骁涵,21020619,06班,20-21下学期高三一模,138.0,136,96.5,370.5,91,99,-,87,-,-,647.5,NaN
1,冯雨辰,21021003,10班,20-21下学期高三一模,124.0,142,94.0,360.0,94,99,-,90,-,-,643.0,NaN
2,尹晓薇,21021025,10班,20-21下学期高三一模,133.5,143,88.5,365.0,97,98,-,82,-,-,642.0,NaN
3,阚紫嫣,21020940,09班,20-21下学期高三一模,125.5,144,93.0,362.5,95,94,-,88,-,-,639.5,NaN
4,张皓天,21020917,09班,20-21下学期高三一模,124.5,142,87.0,353.5,97,98,-,89,-,-,637.5,NaN

In [ ]:
ex

In [13]:
workline = [
  {
    "workLineName": "1%(353.0分)",
    "workLineX": 353
  },
  {
    "workLineName": "3%(344.0分)",
    "workLineX": 344
  },
  {
    "workLineName": "5%(339.0分)",
    "workLineX": 339
  },
  {
    "workLineName": "10%(329.5分)",
    "workLineX": 329
  },
  {
    "workLineName": "20%(315.5分)",
    "workLineX": 315
  },
  {
    "workLineName": "30%(301.5分)",
    "workLineX": 301
  },
  {
    "workLineName": "100%(0.0分)",
    "workLineX": 0
  }
]

workline_list = []
for i in workline:
    workline_list.append(i['workLineX'])

workline_list = workline_list[:-1]
print(workline_list)

[353, 344, 339, 329, 315, 301]

In [73]:
workline_list = [353.0,344.0,339.0,329.5,315.5,301.5]

In [79]:
columns = [353.0,344.0,339.0,329.5,315.5,301.5]
index = exam_info.drop_duplicates(subset='班级',keep='first')['班级'].to_list()
index

['06班',
 '10班',
 '09班',
 '12班',
 '07班',
 '08班',
 '04班',
 '01班',
 '03班',
 '02班',
 '05班',
 '13班']

In [82]:
user_num = []
for i in workline_list:
    user_num.append(len(exam_info[  (exam_info['三科']>=i ) ]['姓名'].to_list()))
print(user_num)

[20, 58, 95, 163, 255, 309]

In [74]:
for i in workline_list:
#     print(exam_info[  (exam_info['三科']>=i )])
#     user_num = []
#     user_num.append() 
#     print('{}：{}人'.format(i,len(exam_info[  (exam_info['三科']>=i ) ]['姓名'].to_list())),exam_info[  (exam_info['三科']>=i ) ]['姓名'].to_list())

353.0：20人 ['谢骁涵', '冯雨辰', '尹晓薇', '阚紫嫣', '张皓天', '吕垒坤', '苗绘', '张睿思', '臧宏之', '郑芊沐', '杨彩航', '张国威', '杨雨鸣', '何美芊', '曹若璇', '李天桓', '高逸文', '苏云鹤', '郭心月', '朴宣蓉']
344.0：58人 ['谢骁涵', '冯雨辰', '尹晓薇', '阚紫嫣', '张皓天', '吕垒坤', '苗绘', '张睿思', '臧宏之', '郑芊沐', '杨彩航', '张国威', '杨雨鸣', '王赛麒', '李弘杰', '何美芊', '林宗翰', '李星熠', '梁葳', '曹若璇', '李天桓', '高逸文', '苏云鹤', '李俊驰', '郭心月', '李思哲', '周畅', '朴宣蓉', '李墨轩', '吴宇桐', '张浩然', '张乐萌', '苏子悦', '徐以舒', '钟嘉杰', '黄俊涛', '宋嘉芸', '王汉骁', '路奕炜', '苏蒙娅', '侯雨初', '王梦嫱', '杜晓萌', '李云洋', '刘雨菲', '马逸静', '肖杨', '杜浦阳', '李一帆', '江健行', '孟祥', '董静怡', '杨万骞', '杜文萱', '王仕湲', '曾玄裔', '吴硕茜', '袁美伊']
339.0：95人 ['谢骁涵', '冯雨辰', '尹晓薇', '阚紫嫣', '张皓天', '吕垒坤', '苗绘', '张睿思', '臧宏之', '郑芊沐', '杨彩航', '张国威', '杨雨鸣', '王赛麒', '李弘杰', '何美芊', '林宗翰', '李星熠', '高奕鹏', '梁葳', '曹若璇', '李天桓', '高逸文', '苏云鹤', '李俊驰', '尹奕涵', '郭心月', '李思哲', '冯屹芃', '张君尚', '卢宇宸', '刘天阳', '周畅', '朴宣蓉', '杨紫元', '李墨轩', '吴宇桐', '张浩然', '张乐萌', '苏子悦', '徐以舒', '何擎天', '钟嘉杰', '包涵', '邹旻昊', '闫咏涵', '吴锡槐', '黄俊涛', '宋嘉芸', '田铭扬', '涂冰洁', '陶湘柠', '李苏艺', '王汉骁', '田艺', '路奕炜', '苏蒙娅', '陈相夷', '董心诣', '温宾显', '侯雨初', '孙雨薇', '王梦嫱', '杜晓萌', '刘正', '李云洋', '刘雨菲', '杨佳忯', '马逸静', '祝雯蕙', '肖杨', '张丰驿', '杜浦阳', '路曾忆', '李一帆', '江健行', '孟祥', '刘梓菁', '董静怡', '杨万骞', '杜文萱', '张宸恺', '王仕湲', '曾玄裔', '邱佳悦', '陈思进', '梁语溪', '胡天意', '牛柯茗', '王子墨', '姚明奕', '吴硕茜', '周雅瑄', '袁美伊', '廖思嘉']
329.5：163人 ['谢骁涵', '冯雨辰', '尹晓薇', '阚紫嫣', '张皓天', '吕垒坤', '苗绘', '张睿思', '臧宏之', '郑芊沐', '杨彩航', '张国威', '杨雨鸣', '王赛麒', '李弘杰', '何美芊', '林宗翰', '李星熠', '高奕鹏', '梁葳', '曹若璇', '李天桓', '高逸文', '苏云鹤', '李俊驰', '尹奕涵', '郭心月', '李思哲', '冯屹芃', '张君尚', '卢宇宸', '刘天阳', '周畅', '朴宣蓉', '杨紫元', '李墨轩', '吴宇桐', '张浩然', '张乐萌', '苏子悦', '徐以舒', '何擎天', '钟嘉杰', '包涵', '邹旻昊', '崔艺文', '王一臻', '闫咏涵', '吴锡槐', '黄俊涛', '宋嘉芸', '张一麟', '田铭扬', '涂冰洁', '王英博', '陶湘柠', '李苏艺', '王汉骁', '田艺', '潘文琦', '路奕炜', '苏蒙娅', '陈相夷', '董心诣', '张睿吉', '温宾显', '张济达', '侯雨初', '孙雨薇', '赵云潇', '解天昊', '王梦嫱', '邹佳毅', '杜晓萌', '刘正', '李云洋', '刘雨菲', '杨佳忯', '赵恩达', '吴芃欣', '谢之楠', '马逸静', '祝雯蕙', '肖杨', '万一', '张丰驿', '杜浦阳', '路曾忆', '王奕诚', '张家宁', '李一帆', '江健行', '孟祥', '赵昕怡', '刘梓菁', '许阳', '李圣心', '王亦秋', '刘紫宜', '王文瑞', '于子淇', '马吉龙', '董静怡', '杨万骞', '杜文萱', '赵弈凡', '张宸恺', '王仕湲', '鄂俊鹏', '张鼎宸', '曾玄裔', '邱佳悦', '程艺芳', '陈思进', '张易从', '向语嫣', '梁语溪', '朱子睎', '胡天意', '李宇硕', '熊佳慧', '吴宇峰', '牛柯茗', '陈裕博', '田然', '王子墨', '姚明奕', '陈嘉玉', '杨心琪', '柴艺桐', '陈怡菲', '魏芊雨', '单烽栩', '康睿卿', '邵奕萌', '朱睿骁', '吴硕茜', '李定棋', '韩夏', '张逸菲', '刘若怡', '赵欣怡', '于世峰', '周雅瑄', '吕骏飞', '张咏言', '王絮', '张梓炫', '袁美伊', '廖思嘉', '张梓涵', '吴佳蕙', '王苑硕', '刘欣欣', '黄晓笛', '戈思文', '赫然', '李景眸', '吕秋媛', '张静娱', '陈奕如', '许成希', '王舒扬']
315.5：255人 ['谢骁涵', '冯雨辰', '尹晓薇', '阚紫嫣', '张皓天', '吕垒坤', '苗绘', '张睿思', '臧宏之', '郑芊沐', '杨彩航', '张国威', '杨雨鸣', '王赛麒', '李弘杰', '何美芊', '林宗翰', '李星熠', '高奕鹏', '梁葳', '曹若璇', '李天桓', '高逸文', '苏云鹤', '李俊驰', '尹奕涵', '郭心月', '李思哲', '冯屹芃', '张君尚', '卢宇宸', '刘天阳', '周畅', '朴宣蓉', '杨紫元', '李墨轩', '吴宇桐', '张浩然', '张乐萌', '苏子悦', '徐以舒', '何擎天', '钟嘉杰', '包涵', '邹旻昊', '崔艺文', '王一臻', '闫咏涵', '吴锡槐', '黄俊涛', '宋嘉芸', '张一麟', '田铭扬', '涂冰洁', '王英博', '陶湘柠', '李苏艺', '王汉骁', '田艺', '潘文琦', '路奕炜', '苏蒙娅', '陈相夷', '董心诣', '张睿吉', '温宾显', '张济达', '侯雨初', '孙雨薇', '赵云潇', '解天昊', '王梦嫱', '邹佳毅', '杜晓萌', '刘正', '李云洋', '刘雨菲', '杨佳忯', '赵恩达', '吴芃欣', '王语瑶', '谢之楠', '王军凯', '马逸静', '祝雯蕙', '肖杨', '万一', '张丰驿', '杜浦阳', '路曾忆', '王奕诚', '张家宁', '李一帆', '江健行', '曹竞峰', '孟祥', '赵昕怡', '刘梓菁', '权尚浩然', '许阳', '李圣心', '王亦秋', '刘紫宜', '王文瑞', '于子淇', '马吉龙', '董静怡', '杨万骞', '杜文萱', '赵弈凡', '张宸恺', '张耀艺', '王仕湲', '鄂俊鹏', '张鼎宸', '曾玄裔', '赵德康', '邱佳悦', '程艺芳', '陈思进', '张易从', '刘浩伦', '向语嫣', '郭湘琦', '梁语溪', '朱子睎', '胡天意', '李宇硕', '秦颖', '熊佳慧', '吴宇峰', '牛柯茗', '高昊', '陈裕博', '张美伊', '田然', '王子墨', '张博博', '姚明奕', '陈嘉玉', '杨心琪', '支凯伦', '吴沛骐', '柴艺桐', '牟笛', '陈怡菲', '栗业', '魏芊雨', '单烽栩', '殷兆杰', '姚缜舒', '郝文欣', '康睿卿', '邵奕萌', '张添一', '项铂中', '钱程', '朱睿骁', '钟昊翔', '吴硕茜', '金俞含', '刘丹华', '李定棋', '杨心芮', '周继昊', '韩夏', '张逸菲', '张天润', '闫盛伦', '刘若怡', '殷乐', '赵欣怡', '赵捷一', '于世峰', '曹艺', '严孚嘉', '周雅瑄', '赵玮一', '张雨璇', '刘欣妍', '吕骏飞', '张咏言', '梁子怡', '王絮', '钟逸', '杨静雯', '薄皓宇', '郑威夷', '瞿嘉辰', '张梓炫', '袁美伊', '陈星竹', '郭笑延', '廖思嘉', '王天保', '马天宇', '张梓涵', '潘浩天', '吴佳蕙', '罗骥', '王苑硕', '刘欣欣', '吴尘', '黄晓笛', '安贺扬', '郑海宁', '王佳程', '丁子恒', '张骥', '戈思文', '赫然', '李景眸', '吕秋媛', '冉心赫', '董震峰', '张静娱', '史昊儒', '沈骁', '张菁', '王语童', '汪正涛', '梁恺', '陈奕如', '卞楚然', '曹雪菲', '张语宣', '包羽霏', '赵彦喆', '姜良婕', '范舒洋', '张姝娢', '邢楚昀', '张嘉翔', '李小岚', '许成希', '周琪蔚', '董霭凝', '赵艺桐', '张艺馨', '武远溪', '王舒扬', '康熠洁', '蔡诗砚', '于玥', '赵可彤云', '唐逸辉', '金潇', '徐沛媛', '朱玄章', '曾媛', '余心悦', '邹路', '徐诚', '赵瑞婷', '郭子菲']
301.5：309人 ['谢骁涵', '冯雨辰', '尹晓薇', '阚紫嫣', '张皓天', '吕垒坤', '苗绘', '张睿思', '臧宏之', '郑芊沐', '杨彩航', '张国威', '杨雨鸣', '王赛麒', '李弘杰', '何美芊', '林宗翰', '李星熠', '高奕鹏', '梁葳', '曹若璇', '李天桓', '高逸文', '苏云鹤', '李俊驰', '尹奕涵', '郭心月', '李思哲', '冯屹芃', '张君尚', '卢宇宸', '刘天阳', '周畅', '朴宣蓉', '杨紫元', '李墨轩', '吴宇桐', '张浩然', '张乐萌', '苏子悦', '徐以舒', '何擎天', '钟嘉杰', '包涵', '邹旻昊', '崔艺文', '王一臻', '闫咏涵', '吴锡槐', '黄俊涛', '宋嘉芸', '张一麟', '田铭扬', '涂冰洁', '王英博', '陶湘柠', '李苏艺', '王汉骁', '田艺', '潘文琦', '路奕炜', '苏蒙娅', '陈相夷', '董心诣', '张睿吉', '温宾显', '张济达', '侯雨初', '孙雨薇', '赵云潇', '解天昊', '王梦嫱', '邹佳毅', '杜晓萌', '刘正', '李云洋', '刘雨菲', '杨佳忯', '赵恩达', '吴芃欣', '王语瑶', '谢之楠', '王军凯', '马逸静', '祝雯蕙', '肖杨', '万一', '张丰驿', '杜浦阳', '路曾忆', '王奕诚', '张家宁', '李一帆', '江健行', '曹竞峰', '孟祥', '赵昕怡', '刘梓菁', '权尚浩然', '许阳', '李圣心', '王亦秋', '刘紫宜', '王文瑞', '于子淇', '马吉龙', '董静怡', '杨万骞', '杜文萱', '赵弈凡', '张宸恺', '张耀艺', '王仕湲', '鄂俊鹏', '张鼎宸', '曾玄裔', '赵德康', '邱佳悦', '程艺芳', '陈思进', '张易从', '刘浩伦', '向语嫣', '郭湘琦', '梁语溪', '朱子睎', '胡天意', '李宇硕', '秦颖', '熊佳慧', '吴宇峰', '牛柯茗', '高昊', '陈裕博', '张美伊', '田然', '王子墨', '张博博', '姚明奕', '陈嘉玉', '杨心琪', '支凯伦', '吴沛骐', '柴艺桐', '牟笛', '陈怡菲', '栗业', '魏芊雨', '单烽栩', '殷兆杰', '姚缜舒', '郝文欣', '康睿卿', '邵奕萌', '张添一', '项铂中', '钱程', '朱睿骁', '钟昊翔', '吴硕茜', '金俞含', '刘丹华', '李定棋', '杨心芮', '周继昊', '韩夏', '张逸菲', '张天润', '闫盛伦', '刘若怡', '殷乐', '赵欣怡', '赵捷一', '于世峰', '曹艺', '严孚嘉', '周雅瑄', '赵玮一', '刘弘晔', '张雨璇', '刘欣妍', '张东方', '张文宇', '吕骏飞', '张咏言', '梁子怡', '王絮', '钟逸', '杨静雯', '薄皓宇', '郑威夷', '瞿嘉辰', '张梓炫', '袁美伊', '陈星竹', '郭笑延', '廖思嘉', '刘骏桐', '王天保', '马天宇', '张梓涵', '张恩宁', '杜静怡', '潘浩天', '吴佳蕙', '罗骥', '王苑硕', '刘欣欣', '吴尘', '黄晓笛', '安贺扬', '郑海宁', '王佳程', '丁子恒', '柳亦然', '张骥', '戈思文', '孔维瑄', '郝伊婧', '赫然', '李景眸', '吕秋媛', '冉心赫', '董震峰', '张静娱', '史昊儒', '沈骁', '杨雨臻', '吴牧晨', '张菁', '王语童', '汪正涛', '梁恺', '陈奕如', '卞楚然', '曹雪菲', '叶馨远', '刘淼轩', '黄奕博', '张语宣', '包羽霏', '赵彦喆', '姜良婕', '范舒洋', '张姝娢', '徐馨岳', '邢楚昀', '张嘉翔', '刘愿辄', '刘小琪', '段舒嘉', '王子山', '李小岚', '许成希', '闫宇', '周琪蔚', '董霭凝', '赵艺桐', '崔盛琳', '张艺馨', '武远溪', '赵茗轩', '王子晨', '王舒扬', '康熠洁', '尚楷博', '汤睿', '陈梓钰', '柴苏昱', '张书阁', '白云芃', '宋雪晴', '蔡诗砚', '于玥', '林志佳', '赵可彤云', '唐逸辉', '马晏飞', '金潇', '徐沛媛', '朱玄章', '张亦弛', '苏月瑶', '陈锦如', '金紫薇', '曾媛', '张雨喆', '余心悦', '邹路', '靳易川', '徐诚', '孙启萱', '奎晟午', '杨懋迪', '赵润禾', '毕海沛', '赵瑞婷', '曾羽敬', '郭子菲', '殷悦然', '李羽涵', '张伟钰', '郑淏', '蔡坦成', '舒一凡', '金秋桐', '刘思羽', '康鑫雨', '俞中一']

In [42]:
exam_info_02 = exam_info[ (exam_info['班级']=='九02班') & (exam_info['三科']>268.0 ) ]
exam_info_02['姓名'].to_list()

['吴迪非',
 '戴雨辰',
 '甘海川',
 '李俊毅',
 '李昭锐',
 '李佳钰',
 '房靖朝',
 '程保晴',
 '吉梦源',
 '魏震源',
 '胡云淏',
 '杨希妍',
 '孙乐涵',
 '张子涵',
 '苏宸辉']

In [18]:
# exam_info_02.to_excel('C:\\Users\\caozhiqiang\\Downloads\\keyi.xls')

In [29]:
lgf_yw = pd.read_excel('C:\\Users\\caozhiqiang\\Desktop\\考试数据分析\\理工附中数据\\20~21第一学期初三期中考试\\254253189784\\1.xlsx',header = 0,skiprows = [0,1,2,3])
lgf_yw['总分'] = lgf_yw.iloc[:,4:].sum(axis=1)
lgf_yw[:]

,区域平均分,Unnamed: 1,Unnamed: 2,Unnamed: 3,1.6233574849564,1.81603831511728,1.8110033157313,1.61156821810144,1.58774407466536,0.714662900650866,...,1.36325678496868,2.3110033157313,0.898624585533587,1.84784477465308,2.16262433992386,1.3524499570183,1.12556797249171,1.10505956035859,33.0087498464939,总分
0,3020140427200509240031,王桐轩,九01班,NaN,2,2,2,2,2,0,...,1,3.0,1,2,2.5,2,1,1,34.0,80.0
1,3020110108200604075723,陈英姿,九01班,NaN,2,2,2,2,2,2,...,2,3.0,1,2,2.5,2,1,1,36.0,88.5
2,3020110105200509078126,刘书毓,九01班,NaN,2,2,0,2,2,2,...,1,3.0,0,2,2.5,2,1,1,34.0,82.0
3,3020110115200604130060,郑伊然,九01班,NaN,2,2,2,2,0,2,...,0,3.0,1,2,3.0,0,1,0,34.5,81.0
4,3020110108200603249525,刘涵依,九01班,NaN,2,2,2,0,2,0,...,0,2.0,1,2,2.5,0,1,1,33.5,71.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,3020110108200605055716,李晟昊,九10班,NaN,0,2,2,2,2,0,...,2,0.5,1,2,1.0,0,0,0,34.0,61.5
350,302011010220060724271X,张炜翔,九10班,NaN,0,1,2,2,0,1,...,2,1.0,1,1,2.0,0,0,3,34.0,64.5
351,3020130626200512212616,张天乐,九10班,NaN,2,2,0,2,0,0,...,0,0.0,0,0,0.0,2,0,1,31.0,48.0
352,3020110112200605271077,张渡祯,九10班,NaN,0,2,0,0,0,0,...,1,0.0,1,0,1.0,2,1,2,13.5,33.0
353,3020110101200601122024,韩卓汐,九10班,NaN,2,2,2,2,2,2,...,2,3.0,1,3,3.5,2,1,3,35.5,92.5

In [52]:
lgf_yw.to_excel('C:\\Users\\caozhiqiang\\Downloads\\keyi.xls')

# 尖子生人数

In [14]:
qy_score = pd.read_excel('C:\\Users\\caozhiqiang\\Desktop\\考试数据分析\\北京四中数据\\20-21第二学期一模考试\\整理数据\\尖子生人数\\区域学科人数.xlsx')
qy_score

,百分比,语文,数学,英语,地理,化学,历史,生物,物理,政治,三科
0,0.0125,55.125,55.125,55.125,25.5125,32.75,19.8,30.5125,39.2125,17.5875,55.125
1,0.0250,110.250,110.250,110.250,51.0250,65.50,39.6,61.0250,78.4250,35.1750,110.250
2,0.0375,165.375,165.375,165.375,76.5375,98.25,59.4,91.5375,117.6375,52.7625,165.375
3,0.0500,220.500,220.500,220.500,102.0500,131.00,79.2,122.0500,156.8500,70.3500,220.500

In [10]:
qy_score['语文'].to_list()

[55.125, 110.25, 165.375, 220.5]

In [11]:
yw_score = qy_score['语文'].to_list()
sx_score = qy_score['数学'].to_list()
yy_score = qy_score['英语'].to_list()
zz_score = qy_score['政治'].to_list()
ls_score = qy_score['历史'].to_list()
dl_score = qy_score['地理'].to_list()
hx_score = qy_score['化学'].to_list()
wl_score = qy_score['物理'].to_list()
sw_score = qy_score['生物'].to_list()
sk_score = qy_score['三科'].to_list()



file_name_list = ['语文','数学','英语','政治','历史','地理','化学','物理','生物','三科']

In [15]:
x = []
y = []


for file_name in file_name_list:
    yw = pd.read_excel('C:\\Users\\caozhiqiang\\Desktop\\考试数据分析\\北京四中数据\\20-21第二学期一模考试\\整理数据\\尖子生人数\\{}.xls'.format(file_name))
    if file_name == '语文':
        yw_list = []
        for i in range(len(yw_score)) :
            
            yw_list.append((yw['地区名次']<= yw_score[i]).value_counts()[True])
        x.append(yw_list)
        
    if file_name == '数学':
        sx_list = []
        for i in range(len(sx_score)) :
            
            sx_list.append((yw['地区名次']<= sx_score[i]).value_counts()[True])
        x.append(sx_list)
            
    if file_name == '英语':
        yy_list = []
        for i in range(len(yy_score)) : 
            yy_list.append((yw['地区名次']<= yy_score[i]).value_counts()[True])
        x.append(yy_list)
        
    if file_name == '政治':
        zz_list = []
        for i in range(len(zz_score)) :
            zz_list.append((yw['地区名次']<= zz_score[i]).value_counts()[True])
        x.append(zz_list)
    if file_name == '历史':
        ls_list = []
        for i in range(len(ls_score)) :
            ls_list.append((yw['地区名次']<= ls_score[i]).value_counts()[True])
        x.append(ls_list)  
    if file_name == '地理':
        dl_list = []
        for i in range(len(dl_score)) :
            dl_list.append((yw['地区名次']<= dl_score[i]).value_counts()[True])
        x.append(dl_list) 
    if file_name == '化学':
        hx_list = []
        for i in range(len(hx_score)) :
            hx_list.append((yw['地区名次']<= hx_score[i]).value_counts()[True])
        x.append(hx_list) 
    if file_name == '物理':
        dl_list = []
        for i in range(len(wl_score)) :
            dl_list.append((yw['地区名次']<= wl_score[i]).value_counts()[True])
        x.append(dl_list)
    if file_name == '生物':
        sw_list = []
        for i in range(len(sw_score)) :
            sw_list.append((yw['地区名次']<= sw_score[i]).value_counts()[True])
        x.append(sw_list)
    if file_name == '三科':
        sk_list = []
        for i in range(len(sk_score)) :
            sk_list.append((yw['地区名次']<= sk_score[i]).value_counts()[True])
        x.append(sk_list)
                   
        
data = pd.DataFrame(x)
data.columns = ['1.25%','2.5%','3.75%','5%']
# data.index = ['语文','数学','英语','政治','历史','地理','化学','物理','生物','三科']
data.index = file_name_list
data

    1.25%  2.5%  3.75%  5%
语文     20    39     58  69
数学     19    48     71  87
英语     23    40     57  78
政治      1     4     11  14
历史      3     8     14  20
地理     16    20     24  24
化学      7    24     44  44
物理     20    33     53  66
生物      9    17     30  42
三科     27    46     68  84

In [ ]:
sz_exam = pd.read_excel('/Users/caozhiqiang/Downloads/北京市第四中学分析.xls')
sz_exam

In [ ]:
sz_exam.info()

In [ ]:
sz_exam[sz_exam['语文'] >= 126.5]

# 5分段人数

In [3]:
exam_list = [
  {
    "objectDisplayName": "本校",
    "objectName": "本校",
    "objectType": 0,
    "pointArray": [
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "1",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "1",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "2",
        "value": "1"
      },
      {
        "name": "4",
        "value": "2"
      },
      {
        "name": "9",
        "value": "4"
      },
      {
        "name": "12",
        "value": "6"
      },
      {
        "name": "15",
        "value": "7"
      },
      {
        "name": "22",
        "value": "11"
      },
      {
        "name": "17",
        "value": "8"
      },
      {
        "name": "16",
        "value": "8"
      },
      {
        "name": "17",
        "value": "8"
      },
      {
        "name": "17",
        "value": "8"
      },
      {
        "name": "14",
        "value": "7"
      },
      {
        "name": "13",
        "value": "6"
      },
      {
        "name": "12",
        "value": "6"
      },
      {
        "name": "6",
        "value": "3"
      },
      {
        "name": "7",
        "value": "3"
      },
      {
        "name": "4",
        "value": "2"
      },
      {
        "name": "4",
        "value": "2"
      },
      {
        "name": "2",
        "value": "1"
      },
      {
        "name": "5",
        "value": "2"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "1",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      },
      {
        "name": "0",
        "value": "0"
      }
    ]
  }
]

for i in exam_list:
#     print(i['pointArray']) 
    name_list = []
    value_list = []

    for p in i['pointArray']:        
        name_list.append(p['name'])
        value_list.append(p['value'])
        
    print(i['objectName'])
    print(name_list)
    print(value_list)

本校
['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '1', '0', '2', '4', '9', '12', '15', '22', '17', '16', '17', '17', '14', '13', '12', '6', '7', '4', '4', '2', '5', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']
['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '2', '4', '6', '7', '11', '8', '8', '8', '8', '7', '6', '6', '3', '3', '2', '2', '1', '2', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']

In [2]:
score_list = [
  "[150,150]",
  "[148,150)",
  "[146,148)",
  "[144,146)",
  "[142,144)",
  "[140,142)",
  "[138,140)",
  "[136,138)",
  "[134,136)",
  "[132,134)",
  "[130,132)",
  "[128,130)",
  "[126,128)",
  "[124,126)",
  "[122,124)",
  "[120,122)",
  "[118,120)",
  "[116,118)",
  "[114,116)",
  "[112,114)",
  "[110,112)",
  "[108,110)",
  "[106,108)",
  "[104,106)",
  "[102,104)",
  "[100,102)",
  "[98,100)",
  "[96,98)",
  "[94,96)",
  "[92,94)",
  "[90,92)",
  "[88,90)",
  "[86,88)",
  "[84,86)",
  "[82,84)",
  "[80,82)",
  "[78,80)",
  "[76,78)",
  "[74,76)",
  "[72,74)",
  "[70,72)",
  "[68,70)",
  "[66,68)",
  "[64,66)",
  "[62,64)",
  "[60,62)",
  "[58,60)",
  "[56,58)",
  "[54,56)",
  "[52,54)",
  "[50,52)",
  "[48,50)",
  "[46,48)",
  "[44,46)",
  "[42,44)",
  "[40,42)",
  "[38,40)",
  "[36,38)",
  "[34,36)",
  "[32,34)",
  "[30,32)",
  "[28,30)",
  "[26,28)",
  "[24,26)",
  "[22,24)",
  "[20,22)",
  "[18,20)",
  "[16,18)",
  "[14,16)",
  "[12,14)",
  "[10,12)",
  "[8,10)",
  "[6,8)",
  "[4,6)",
  "[2,4)",
  "[0,2)"
]
print(score_list)

['[150,150]', '[148,150)', '[146,148)', '[144,146)', '[142,144)', '[140,142)', '[138,140)', '[136,138)', '[134,136)', '[132,134)', '[130,132)', '[128,130)', '[126,128)', '[124,126)', '[122,124)', '[120,122)', '[118,120)', '[116,118)', '[114,116)', '[112,114)', '[110,112)', '[108,110)', '[106,108)', '[104,106)', '[102,104)', '[100,102)', '[98,100)', '[96,98)', '[94,96)', '[92,94)', '[90,92)', '[88,90)', '[86,88)', '[84,86)', '[82,84)', '[80,82)', '[78,80)', '[76,78)', '[74,76)', '[72,74)', '[70,72)', '[68,70)', '[66,68)', '[64,66)', '[62,64)', '[60,62)', '[58,60)', '[56,58)', '[54,56)', '[52,54)', '[50,52)', '[48,50)', '[46,48)', '[44,46)', '[42,44)', '[40,42)', '[38,40)', '[36,38)', '[34,36)', '[32,34)', '[30,32)', '[28,30)', '[26,28)', '[24,26)', '[22,24)', '[20,22)', '[18,20)', '[16,18)', '[14,16)', '[12,14)', '[10,12)', '[8,10)', '[6,8)', '[4,6)', '[2,4)', '[0,2)']

# 等级赋分

In [232]:
rank_score_excel = pd.read_excel('C:\\Users\\caozhiqiang\\Desktop\\考试数据分析\\北京四中数据\\20-21第二学期一模考试\\整理数据\\等级赋分\\等级赋分表.xlsx')
rank_score_excel

    赋分成绩  物理  化学  生物    历史    地理    政治
0    100  96  99  89  86.5  89.0  86.0
1     97  94  97  86  84.0  87.0  83.0
2     94  91  95  82  80.5  83.0  80.5
3     91  88  94  79  78.0  81.5  78.0
4     88  84  92  76  75.5  80.0  75.5
5     85  80  89  73  73.5  77.5  72.5
6     82  74  84  70  70.0  75.0  70.0
7     79  68  78  66  67.0  72.0  67.5
8     76  64  73  63  63.5  68.5  64.5
9     73  60  69  59  61.5  65.5  62.0
10    70  55  65  56  58.5  64.0  60.0
11    67  51  61  53  56.5  61.0  57.0
12    64  49  57  50  53.5  57.5  53.5
13    61  45  52  46  50.5  54.0  51.5
14    58  41  47  42  46.5  51.0  47.0
15    55  37  43  38  43.5  47.5  44.5
16    52  32  36  33  38.0  43.0  37.0
17    49  28  29  30  29.0  36.0  32.0
18    46  23  24  24  25.0  34.0  29.0
19    43  20  20  22  23.0  28.0  22.0
20    40  14  12  11  14.5  12.0   9.0

In [239]:
stu_exam = pd.read_excel('C:\\Users\\caozhiqiang\\Desktop\\考试数据分析\\北京四中数据\\20-21第二学期一模考试\\整理数据\\等级赋分\\四中一模成绩单.xlsx')
stu_exam = stu_exam.fillna(0)
stu_exam

,姓名,学号,班级,考试名称,语文,数学,英语,英语听力,三科,物理,...,地理,政治,全科,物赋分,化赋分,政赋分,历赋分,生赋分,地赋分,赋分总分
0,谢骁涵,21020619,06班,20-21下学期高三一模,138.0,136,96.5,50,370.5,91.0,...,0.0,0.0,647.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,冯雨辰,21021003,10班,20-21下学期高三一模,124.0,142,94.0,50,360.0,94.0,...,0.0,0.0,643.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,尹晓薇,21021025,10班,20-21下学期高三一模,133.5,143,88.5,50,365.0,97.0,...,0.0,0.0,642.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,阚紫嫣,21020940,09班,20-21下学期高三一模,125.5,144,93.0,50,362.5,95.0,...,0.0,0.0,639.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,张皓天,21020917,09班,20-21下学期高三一模,124.5,142,87.0,50,353.5,97.0,...,0.0,0.0,637.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,于世奇,21020509,05班,20-21下学期高三一模,95.0,92,66.5,48.5,253.5,0.0,...,52.0,72.0,442.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
360,席振钧,21020507,05班,20-21下学期高三一模,92.5,92,63.0,47.5,247.5,70.0,...,0.0,61.0,441.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0
361,冯荷华,21020312,03班,20-21下学期高三一模,95.0,83,69.0,48,247.0,67.0,...,0.0,0.0,440.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
362,刘明姗,21020512,05班,20-21下学期高三一模,95.5,92,65.5,49,253.0,56.0,...,64.0,0.0,437.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0
363,胡天龙,21020108,01班,20-21下学期高三一模,98.0,87,44.0,42,229.0,53.0,...,57.0,0.0,406.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [240]:
def rank_score(score,rank_score):

    if score >= rank_score[0]:

        return 100
    elif score >= rank_score[1] and score<rank_score[0]:
        return 97
    elif score >= rank_score[2] and score<rank_score[1]:
        return 94
    elif score >= rank_score[3] and score<rank_score[2]:
        return 91
    elif score >= rank_score[4] and score<rank_score[3]:
        return 88
    elif score >= rank_score[5] and score<rank_score[4]:
        return 85
    elif score >= rank_score[6] and score<rank_score[5]:
        return 82
    elif score >= rank_score[7] and score<rank_score[6]:
        return 79
    elif score >= rank_score[8] and score<rank_score[7]:
        return 76
    elif score >= rank_score[9] and score<rank_score[8]:
        return 73
    elif score >= rank_score[10] and score<rank_score[9]:
        return 70
    elif score >= rank_score[11] and score<rank_score[10]:
        return 67
    elif score >= rank_score[12] and score<rank_score[11]:
        return 64
    elif score >= rank_score[13] and score<rank_score[12]:
        return 61
    elif score >= rank_score[14] and score<rank_score[13]:
        return 58
    elif score >= rank_score[15] and score<rank_score[14]:
        return 55
    elif score >= rank_score[16] and score<rank_score[15]:
        return 52
    elif score >= rank_score[17] and score<rank_score[16]:
        return 49
    elif score >= rank_score[18] and score<rank_score[17]:
        return 46
    elif score >= rank_score[19] and score<rank_score[18]:
        return 43
    elif score >= rank_score[20] and score<rank_score[19]:
        return 40

In [241]:
wl_rank_score = rank_score_excel['物理'].to_list()
hx_rank_score = rank_score_excel['化学'].to_list()
ls_rank_score = rank_score_excel['历史'].to_list()
sw_rank_score = rank_score_excel['生物'].to_list()
dl_rank_score = rank_score_excel['地理'].to_list()
zz_rank_score = rank_score_excel['政治'].to_list()


stu_exam['物赋分'] = stu_exam['物理'].apply(lambda x: rank_score(x,rank_score=wl_rank_score) )
stu_exam['化赋分'] = stu_exam['化学'].apply(lambda x: rank_score(x,rank_score=hx_rank_score) )
stu_exam['政赋分'] = stu_exam['政治'].apply(lambda x: rank_score(x,rank_score=zz_rank_score) )
stu_exam['历赋分'] = stu_exam['历史'].apply(lambda x: rank_score(x,rank_score=ls_rank_score) )
stu_exam['生赋分'] = stu_exam['生物'].apply(lambda x: rank_score(x,rank_score=sw_rank_score) )
stu_exam['地赋分'] = stu_exam['地理'].apply(lambda x: rank_score(x,rank_score=dl_rank_score) )

stu_exam

,姓名,学号,班级,考试名称,语文,数学,英语,英语听力,三科,物理,...,地理,政治,全科,物赋分,化赋分,政赋分,历赋分,生赋分,地赋分,赋分总分
0,谢骁涵,21020619,06班,20-21下学期高三一模,138.0,136,96.5,50,370.5,91.0,...,0.0,0.0,647.5,94.0,100.0,NaN,NaN,97.0,NaN,0.0
1,冯雨辰,21021003,10班,20-21下学期高三一模,124.0,142,94.0,50,360.0,94.0,...,0.0,0.0,643.0,97.0,100.0,NaN,NaN,100.0,NaN,0.0
2,尹晓薇,21021025,10班,20-21下学期高三一模,133.5,143,88.5,50,365.0,97.0,...,0.0,0.0,642.0,100.0,97.0,NaN,NaN,94.0,NaN,0.0
3,阚紫嫣,21020940,09班,20-21下学期高三一模,125.5,144,93.0,50,362.5,95.0,...,0.0,0.0,639.5,97.0,91.0,NaN,NaN,97.0,NaN,0.0
4,张皓天,21020917,09班,20-21下学期高三一模,124.5,142,87.0,50,353.5,97.0,...,0.0,0.0,637.5,100.0,97.0,NaN,NaN,100.0,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,于世奇,21020509,05班,20-21下学期高三一模,95.0,92,66.5,48.5,253.5,0.0,...,52.0,72.0,442.0,NaN,NaN,82.0,76.0,NaN,58.0,0.0
360,席振钧,21020507,05班,20-21下学期高三一模,92.5,92,63.0,47.5,247.5,70.0,...,0.0,61.0,441.5,79.0,NaN,70.0,73.0,NaN,NaN,0.0
361,冯荷华,21020312,03班,20-21下学期高三一模,95.0,83,69.0,48,247.0,67.0,...,0.0,0.0,440.0,76.0,67.0,NaN,NaN,76.0,NaN,0.0
362,刘明姗,21020512,05班,20-21下学期高三一模,95.5,92,65.5,49,253.0,56.0,...,64.0,0.0,437.5,70.0,NaN,NaN,76.0,NaN,70.0,0.0
363,胡天龙,21020108,01班,20-21下学期高三一模,98.0,87,44.0,42,229.0,53.0,...,57.0,0.0,406.0,67.0,NaN,NaN,NaN,79.0,61.0,0.0

In [191]:
stu_exam.to_excel('C:\\Users\\caozhiqiang\\Downloads\\赋分后数据.xls')

In [268]:
qm_stu_exam = pd.read_excel('C:\\Users\\caozhiqiang\\Desktop\\考试数据分析\\北京四中数据\\20-21第一学期高三期末考试\\数据整理\\等级赋分\\期末考试学生名单.xlsx',sheet_name = 'sheet1')
qm_rank_score = pd.read_excel('C:\\Users\\caozhiqiang\\Desktop\\考试数据分析\\北京四中数据\\20-21第一学期高三期末考试\\数据整理\\等级赋分\\期末考试学生名单.xlsx',sheet_name = '等级赋分表')

In [261]:
qm_stu_exam

,姓名,学号,班级,考试名称,语文,数学,英语,三科,物理,化学,...,地理,政治,原始分总分,物赋分,化赋分,历赋分,生赋分,地赋分,政赋分,赋分总分
0,李俊驰,21021010,10班,20-21上学期高三期末,121.0,149,91.0,361.0,93,97,...,0,0,647.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,张皓天,21020917,09班,20-21上学期高三期末,126.0,138,91.5,355.5,97,97,...,0,0,642.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,张睿思,21021030,10班,20-21上学期高三期末,127.5,145,90.5,363.0,92,90,...,97,0,642.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,解天昊,21020620,06班,20-21上学期高三期末,121.0,142,92.5,355.5,96,92,...,0,0,641.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,杜文萱,21021256,12班,20-21上学期高三期末,129.5,138,92.0,359.5,0,0,...,93,97,640.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,张楠,21020406,04班,20-21上学期高三期末,106.5,99,70.5,276.0,54,64,...,0,0,462.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
360,冯荷华,21020312,03班,20-21上学期高三期末,82.0,96,82.0,260.0,62,61,...,0,0,448.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
361,胡天龙,21020108,01班,20-21上学期高三期末,105.0,83,64.5,252.5,55,0,...,59,0,437.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
362,席振钧,21020507,05班,20-21上学期高三期末,102.0,0,0.0,102.0,0,0,...,0,61,163.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
363,赵子垚,21020309,03班,20-21上学期高三期末,86.5,0,0.0,86.5,0,0,...,0,0,125.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [269]:
qm_rank_score

    赋分成绩  物理  化学  生物    历史  地理  政治
0    100  98  96  93  89.5  95  92
1     97  94  94  90  87.0  93  89
2     94  89  92  87  83.5  90  86
3     91  85  90  84  81.0  88  83
4     88  81  88  81  78.5  85  81
5     85  77  83  77  76.0  82  77
6     82  72  79  73  72.0  79  74
7     79  68  73  69  70.0  76  71
8     76  64  68  66  66.5  72  67
9     73  58  64  62  64.0  69  65
10    70  55  61  59  61.0  67  63
11    67  51  57  57  59.0  64  60
12    64  48  53  55  56.5  61  57
13    61  43  48  49  54.0  58  54
14    58  38  44  45  51.0  54  49
15    55  35  40  42  48.0  50  46
16    52  28  34  36  44.5  47  41
17    49  24  27  31  41.5  42  36
18    46  17  23  24  37.0  34  29
19    43  14  19  21  33.5  29  18
20    40   6  12   6  24.0  15  14

In [270]:
wl_rank_score = qm_rank_score['物理'].to_list()
hx_rank_score = qm_rank_score['化学'].to_list()
ls_rank_score = qm_rank_score['历史'].to_list()
sw_rank_score = qm_rank_score['生物'].to_list()
dl_rank_score = qm_rank_score['地理'].to_list()
zz_rank_score = qm_rank_score['政治'].to_list()


qm_stu_exam['物赋分'] = qm_stu_exam['物理'].apply(lambda x: rank_score(x,rank_score=wl_rank_score) )
qm_stu_exam['化赋分'] = qm_stu_exam['化学'].apply(lambda x: rank_score(x,rank_score=hx_rank_score) )
qm_stu_exam['政赋分'] = qm_stu_exam['政治'].apply(lambda x: rank_score(x,rank_score=zz_rank_score) )
qm_stu_exam['历赋分'] = qm_stu_exam['历史'].apply(lambda x: rank_score(x,rank_score=ls_rank_score) )
qm_stu_exam['生赋分'] = qm_stu_exam['生物'].apply(lambda x: rank_score(x,rank_score=sw_rank_score) )
qm_stu_exam['地赋分'] = qm_stu_exam['地理'].apply(lambda x: rank_score(x,rank_score=dl_rank_score) )

qm_stu_exam

,姓名,学号,班级,考试名称,语文,数学,英语,三科,物理,化学,...,地理,政治,原始分总分,物赋分,化赋分,历赋分,生赋分,地赋分,政赋分,赋分总分
0,李俊驰,21021010,10班,20-21上学期高三期末,121.0,149,91.0,361.0,93,97,...,0,0,647.0,94.0,100.0,NaN,100.0,NaN,NaN,NaN
1,张皓天,21020917,09班,20-21上学期高三期末,126.0,138,91.5,355.5,97,97,...,0,0,642.5,97.0,100.0,NaN,100.0,NaN,NaN,NaN
2,张睿思,21021030,10班,20-21上学期高三期末,127.5,145,90.5,363.0,92,90,...,97,0,642.0,94.0,91.0,NaN,NaN,100.0,NaN,NaN
3,解天昊,21020620,06班,20-21上学期高三期末,121.0,142,92.5,355.5,96,92,...,0,0,641.5,97.0,94.0,NaN,100.0,NaN,NaN,NaN
4,杜文萱,21021256,12班,20-21上学期高三期末,129.5,138,92.0,359.5,0,0,...,93,97,640.5,NaN,NaN,100.0,NaN,97.0,100.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,张楠,21020406,04班,20-21上学期高三期末,106.5,99,70.5,276.0,54,64,...,0,0,462.0,67.0,73.0,NaN,76.0,NaN,NaN,NaN
360,冯荷华,21020312,03班,20-21上学期高三期末,82.0,96,82.0,260.0,62,61,...,0,0,448.0,73.0,70.0,NaN,73.0,NaN,NaN,NaN
361,胡天龙,21020108,01班,20-21上学期高三期末,105.0,83,64.5,252.5,55,0,...,59,0,437.5,70.0,NaN,NaN,79.0,61.0,NaN,NaN
362,席振钧,21020507,05班,20-21上学期高三期末,102.0,0,0.0,102.0,0,0,...,0,61,163.0,NaN,NaN,NaN,NaN,NaN,67.0,NaN
363,赵子垚,21020309,03班,20-21上学期高三期末,86.5,0,0.0,86.5,0,0,...,0,0,125.5,NaN,NaN,NaN,52.0,NaN,NaN,NaN

In [271]:
qm_stu_exam.to_excel('C:\\Users\\caozhiqiang\\Downloads\\期末赋分后数据.xls')

# pyecharts

In [1]:
from pyecharts.globals import CurrentConfig, NotebookType
CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_LAB

In [ ]:
#渲染图大小
line = Line(init_opts = opts.InitOpts(width = '1200px'))

#X轴数据
line.add_xaxis(school_course_task_x)
#Y轴名称和数据
line.add_yaxis("任务数量", school_course_task_y)

# 全局配置
line.set_global_opts(
    #主标题
    title_opts=opts.TitleOpts(title="每天任务趋势图"),
    # 缩放功能
    datazoom_opts = opts.DataZoomOpts( is_show = True , type_ ='slider',range_start = 70,range_end = 100),
    # x轴文字距离，旋转角度
    
    xaxis_opts=opts.AxisOpts(
            axislabel_opts={"interval":"0","rotate":45},
        ),
    
    tooltip_opts=opts.TooltipOpts(trigger="axis"),

#     xaxis_opts=opts.AxisOpts(type_="category", boundary_gap=False,name_rotate=45,),
    
)

# 系统配置
line.set_series_opts(
    # 图中显示数值
    label_opts = opts.LabelOpts(is_show=True),

    # 线装图，平均线
    markline_opts=opts.MarkLineOpts(
        data=[opts.MarkLineItem(type_="average", name="平均值"),]
                                    ),
    # 点装图，最大值最小值
    markpoint_opts=opts.MarkPointOpts(
            data=[
                opts.MarkPointItem(type_="min", name="最小值"),
                opts.MarkPointItem(type_="max", name="最大值"),
            ]
        ),
)

In [58]:
from pyecharts.charts import Bar
from pyecharts import options as opts

bar = Bar(init_opts=opts.InitOpts(width='1500px',height='600px'))
bar.set_global_opts(xaxis_opts=opts.AxisOpts(
            axislabel_opts={"interval":"0","rotate":45},
        ),)

bar.add_xaxis(
    ['[100,100]', '[98,100)', '[96,98)', '[94,96)', '[92,94)', '[90,92)', '[88,90)', '[86,88)', '[84,86)', '[82,84)', '[80,82)', '[78,80)', '[76,78)', '[74,76)', '[72,74)', '[70,72)', '[68,70)', '[66,68)', '[64,66)', '[62,64)', '[60,62)', '[58,60)', '[56,58)', '[54,56)', '[52,54)', '[50,52)', '[48,50)', '[46,48)', '[44,46)', '[42,44)', '[40,42)', '[38,40)', '[36,38)', '[34,36)', '[32,34)', '[30,32)', '[28,30)', '[26,28)', '[24,26)', '[22,24)', '[20,22)', '[18,20)', '[16,18)', '[14,16)', '[12,14)', '[10,12)', '[8,10)', '[6,8)', '[4,6)', '[2,4)', '[0,2)']


)
bar.add_yaxis("地理", 
   ['0', '0', '0', '0', '0', '0', '2', '1', '1', '8', '20', '29', '39', '54', '51', '47', '50', '48', '46', '40', '33', '25', '11', '18', '8', '4', '7', '0', '2', '1', '2', '0', '0', '0', '1', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']
   
)

bar.load_javascript()
bar.render('地理.html')

'F:\\PythonObject\\jupyter\\地理.html'

# get

In [1]:
import requests 
import json

In [3]:
url = 'https://school-cloud.etiantian.com/school-statistics/exam-analysis/school-area-score-multiple-line?'

In [4]:
data = json.dumps({'examId':'1877756070162','compareType':'2','compareExamArray':'','objectTypes':[-1,0,2,4],'examSubjectId':'2','token':'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXRhaWwiOnsidXNlcklkIjoyOTUxNjM1LCJ1c2VyTmFtZSI6IuWkp-i_nua1i-ivlTAwMSIsInBhc3N3b3JkIjoiIiwidXNlcklkZW50aXR5IjoxLCJlbmFibGUiOjEsInNjaG9vbFVzZXJJZCI6MzY3Njg2LCJzY2hvb2xJZCI6NTAwNDMsInNjaG9vbFVzZXJSZWYiOiJmYzI4Y2IwYi1lMDRmLTQ0ODUtOTQ4Yi02M2Q0NTU2ZmNlNGEiLCJzY2hvb2xHcm91cElkIjo3LCJyb2xlcyI6WzE2LDE3LDIsMjEsNiw5LDEzLDE1XSwidXJsTGlzdCI6bnVsbH0sImV4cCI6MTYyMDMwNDg3MSwidXNlcl9uYW1lIjoi5aSn6L-e5rWL6K-VMDAxIiwianRpIjoiYzZmYzZhZTYtNDhhYS00YjZlLTlmNzQtZjFmZjJjMDdlYzRlIiwiY2xpZW50X2lkIjoiRkE5RTIxNUJFNTY2RUU5MjYxNEZCQzExQUJFREY5NjgiLCJzY29wZSI6WyJhbGwiLCJ3ZWIiLCJtb2JpbGUiXX0.yTqb-3YY_sg5NG_Gi9ve23shM5-dEddLlp86kvOLgnY'})

In [8]:
get_url = 'https://school-cloud.etiantian.com/school-statistics/exam-analysis/school-area-score-multiple-line?examId=346769174074&compareType=4&compareExamArray=&objectTypes=0,2&r=0.2526140433758095&examSubjectId=1&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXRhaWwiOnsidXNlcklkIjoyOTUxNjM1LCJ1c2VyTmFtZSI6IuWkp-i_nua1i-ivlTAwMSIsInBhc3N3b3JkIjoiIiwidXNlcklkZW50aXR5IjoxLCJlbmFibGUiOjEsInNjaG9vbFVzZXJJZCI6MzY3Njg2LCJzY2hvb2xJZCI6NTAwNDMsInNjaG9vbFVzZXJSZWYiOiJmYzI4Y2IwYi1lMDRmLTQ0ODUtOTQ4Yi02M2Q0NTU2ZmNlNGEiLCJzY2hvb2xHcm91cElkIjo3LCJyb2xlcyI6WzE2LDE3LDIsMjEsNiw5LDEzLDE1XSwidXJsTGlzdCI6bnVsbH0sImV4cCI6MTYyMDY0NjgwOSwidXNlcl9uYW1lIjoi5aSn6L-e5rWL6K-VMDAxIiwianRpIjoiM2MzYTBmYzEtNGIwYi00ODllLWI2YTYtNjg4ZDM5OGI5MGUwIiwiY2xpZW50X2lkIjoiRkE5RTIxNUJFNTY2RUU5MjYxNEZCQzExQUJFREY5NjgiLCJzY29wZSI6WyJhbGwiLCJ3ZWIiLCJtb2JpbGUiXX0.3-ey4CzNjlU4QsYEIWFoZI5vfaXf2V6unmzSU6K2Exk'
# requests.request('get',get_url)
ret = requests.get(url=get_url)
text = json.loads(ret.text)
print(text)

{'code': 1, 'data': {'pointXList': ['[150,150]', '[148,150)', '[146,148)', '[144,146)', '[142,144)', '[140,142)', '[138,140)', '[136,138)', '[134,136)', '[132,134)', '[130,132)', '[128,130)', '[126,128)', '[124,126)', '[122,124)', '[120,122)', '[118,120)', '[116,118)', '[114,116)', '[112,114)', '[110,112)', '[108,110)', '[106,108)', '[104,106)', '[102,104)', '[100,102)', '[98,100)', '[96,98)', '[94,96)', '[92,94)', '[90,92)', '[88,90)', '[86,88)', '[84,86)', '[82,84)', '[80,82)', '[78,80)', '[76,78)', '[74,76)', '[72,74)', '[70,72)', '[68,70)', '[66,68)', '[64,66)', '[62,64)', '[60,62)', '[58,60)', '[56,58)', '[54,56)', '[52,54)', '[50,52)', '[48,50)', '[46,48)', '[44,46)', '[42,44)', '[40,42)', '[38,40)', '[36,38)', '[34,36)', '[32,34)', '[30,32)', '[28,30)', '[26,28)', '[24,26)', '[22,24)', '[20,22)', '[18,20)', '[16,18)', '[14,16)', '[12,14)', '[10,12)', '[8,10)', '[6,8)', '[4,6)', '[2,4)', '[0,2)'], 'polyLines': [{'objectDisplayName': '本校', 'objectName': '本校', 'objectType': 0, 'pointArray': [{'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '1', 'value': '0'}, {'name': '2', 'value': '0'}, {'name': '5', 'value': '1'}, {'name': '14', 'value': '3'}, {'name': '20', 'value': '4'}, {'name': '31', 'value': '6'}, {'name': '52', 'value': '9'}, {'name': '50', 'value': '9'}, {'name': '59', 'value': '11'}, {'name': '59', 'value': '11'}, {'name': '55', 'value': '10'}, {'name': '45', 'value': '8'}, {'name': '45', 'value': '8'}, {'name': '23', 'value': '4'}, {'name': '17', 'value': '3'}, {'name': '15', 'value': '3'}, {'name': '11', 'value': '2'}, {'name': '6', 'value': '1'}, {'name': '9', 'value': '2'}, {'name': '5', 'value': '1'}, {'name': '5', 'value': '1'}, {'name': '5', 'value': '1'}, {'name': '2', 'value': '0'}, {'name': '3', 'value': '1'}, {'name': '2', 'value': '0'}, {'name': '1', 'value': '0'}, {'name': '1', 'value': '0'}, {'name': '1', 'value': '0'}, {'name': '1', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '1', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '1', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '1', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '1', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}, {'name': '0', 'value': '0'}]}], 'scoreStep': 2, 'totalScore': '150', 'workLines': [{'workLineName': '1%(134.52分)', 'workLineX': 134}, {'workLineName': '3%(132.0分)', 'workLineX': 132}, {'workLineName': '5%(131.0分)', 'workLineX': 131}, {'workLineName': '10%(128.2分)', 'workLineX': 128}, {'workLineName': '20%(126.0分)', 'workLineX': 126}, {'workLineName': '30%(124.0分)', 'workLineX': 124}, {'workLineName': '100%(20.0分)', 'workLineX': 20}]}, 'msg': '操作成功'}

In [9]:
x_list = []
for i in text['data']['pointXList']:
    x_list.append(i)
print(x_list)

['[150,150]', '[148,150)', '[146,148)', '[144,146)', '[142,144)', '[140,142)', '[138,140)', '[136,138)', '[134,136)', '[132,134)', '[130,132)', '[128,130)', '[126,128)', '[124,126)', '[122,124)', '[120,122)', '[118,120)', '[116,118)', '[114,116)', '[112,114)', '[110,112)', '[108,110)', '[106,108)', '[104,106)', '[102,104)', '[100,102)', '[98,100)', '[96,98)', '[94,96)', '[92,94)', '[90,92)', '[88,90)', '[86,88)', '[84,86)', '[82,84)', '[80,82)', '[78,80)', '[76,78)', '[74,76)', '[72,74)', '[70,72)', '[68,70)', '[66,68)', '[64,66)', '[62,64)', '[60,62)', '[58,60)', '[56,58)', '[54,56)', '[52,54)', '[50,52)', '[48,50)', '[46,48)', '[44,46)', '[42,44)', '[40,42)', '[38,40)', '[36,38)', '[34,36)', '[32,34)', '[30,32)', '[28,30)', '[26,28)', '[24,26)', '[22,24)', '[20,22)', '[18,20)', '[16,18)', '[14,16)', '[12,14)', '[10,12)', '[8,10)', '[6,8)', '[4,6)', '[2,4)', '[0,2)']

In [10]:
for i in text['data']['polyLines']:
#     print(i)
    name_list=[]
    value_list=[]
    for p in i['pointArray']:        
        name_list.append(p['name'])
        value_list.append(p['value'])
    print(i['objectName'])
    print(name_list)
    print(value_list)

本校
['0', '0', '0', '0', '0', '0', '1', '2', '5', '14', '20', '31', '52', '50', '59', '59', '55', '45', '45', '23', '17', '15', '11', '6', '9', '5', '5', '5', '2', '3', '2', '1', '1', '1', '1', '0', '0', '1', '0', '0', '0', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']
['0', '0', '0', '0', '0', '0', '0', '0', '1', '3', '4', '6', '9', '9', '11', '11', '10', '8', '8', '4', '3', '3', '2', '1', '2', '1', '1', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']